# Generated by Django 6.0.1 on 2026-03-18 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongGenRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=50)),
                ('mood', models.CharField(choices=[('happy', 'happy'), ('energatic', 'energatic'), ('sad', 'sad'), ('depression', 'depression'), ('calm', 'calm')], default='happy', max_length=10)),
                ('genre', models.CharField(choices=[('pop', 'pop'), ('rock', 'rock'), ('jazz', 'jazz'), ('classical', 'classical'), ('electronic', 'electronic'), ('hiphop', 'hiphop'), ('country', 'country'), ('metal', 'metal')], default='pop', max_length=10)),
                ('occasion', models.CharField(max_length=50)),
                ('singer_voice_type', models.CharField(max_length=50)),
                ('optional_story', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('song', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='song_gen_request', to='song.song')),
            ],
            options={
                'db_table': 'song_gen_request',
            },
        ),
    ]
