# Generated by Django 6.0.1 on 2026-03-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='daily_gen_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
