# Generated by Django 6.0.3 on 2026-04-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_daily_gen_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='daily_gen_count',
            field=models.IntegerField(default=20),
        ),
    ]
