# Generated by Django 6.0.3 on 2026-04-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_link', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedlink',
            name='shared_url',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
