# Generated by Django 6.0.3 on 2026-04-17 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_alter_song_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='generation_status',
        ),
    ]
