# Generated by Django 6.0.3 on 2026-04-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0004_remove_song_generation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
