# Generated by Django 6.0.1 on 2026-03-22 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_initial'),
        ('song_gen_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songgenrequest',
            name='song',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song_gen_request', to='song.song'),
        ),
    ]
