# Generated by Django 6.0.3 on 2026-04-17 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_gen_request', '0002_alter_songgenrequest_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='songgenrequest',
            name='generation_status',
            field=models.CharField(choices=[('success', 'success'), ('failed', 'failed'), ('pending', 'pending')], default='pending', max_length=7),
        ),
        migrations.AddField(
            model_name='songgenrequest',
            name='task_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
